apiVersion: v1
kind: Secret
metadata:
    name: c2xc-agent-api-key
    namespace: c2xc
type: Opaque
stringData:
    #ENC[AES256_GCM,data:eQ0Q+KtVHrqPNIgHjrKChAYetzaG5+k5p1RY79XBwyOjmZ8=,iv:+m/NPgd3jGcQhhYCTkxx2pfLJnDAdGG8wFgdunS6c5Y=,tag:eBM0g5hyDLe6J3uXSXc7Sw==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:YD9MeoUFIauJryrneJV0xRxTYj6jB3lUkr8v4+CYSQYyUNo=,iv:y1y5J1Q1I13bvprTqK3XZEFjbGtqjmamxMkYr5IzHuQ=,tag:N+bNCop66sAlEw6v86O5cA==,type:str]
    C2XC_EMBEDDING_API_KEY: ENC[AES256_GCM,data:g5I7aIKwZKh4QoE9cswQAZGHMf/rPh+HjDud07iKRK0VRMc=,iv:Tu2Mr7Wo4u6x4Y18kqExVjxuK6CyDId8lhmY1iBesjY=,tag:P/nz96yZpixB3nLnz6uFkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7psnl4m7ttpwue84y6fsfr5075awz94h8frqm4d6q35xq9xjyjs3dtvn5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVUVXYkdyRVdiNzBNQ1hH
            M2tBSHV0a29maFhGVC9MR25vQVp4RjM5L0ZzCm8rT0RmcHh2UVhrdS9yUVFtR3RK
            Q01LbTBCVXpjS2NWWEkzd2N6elF4VEkKLS0tIDFjVFNzRTF2OHpmNTlMY0o0eFMx
            QjlIaTVNbmsxOU9aSVhMUGtiRTRON1EKqmzCaZgSRIbuacHcIpxqsCYapWVivHcb
            DOfASfrB+JdKD0ZCp9G/6LqTONzOKldzRnhxFC9cOKUdgD6SOfRx4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T11:19:31Z"
    mac: ENC[AES256_GCM,data:a7GBkP4U5tUUqq39SL+6UPXOJI/hy3GSeiaDYpPIGXMztmP0QC4zWqjBA+aMciH+uoT97CQ+juIMfS+XlqazJqccD8Lir1al5bzWTmmWTCnk3F2OCIO2lEFeb97huGtzexh4L3vgsnCG1m1suzFdc+JOhKqJQRZWQ/gdepvDDo0=,iv:Mau8OlRG1kACGqHui0MZ95fF+1phWcf3+daYtsHVRP8=,tag:aVQSo4Bs8fYrIPIcb7IhgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
