apiVersion: v1
kind: Secret
metadata:
    name: c2xc-agent-api-key
    namespace: custom-app
type: Opaque
stringData:
    #ENC[AES256_GCM,data:mE2SkYI73MzfVu6zpZUmCvje494UfMp0oxTFtL6CNGmmOow=,iv:ZGMue65mw3jbLGNgWjXCVYPkb4h5W+ME5FmBpmqczkI=,tag:VHEOqDrJbO6jEv/SsF7BJg==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Adtj1yROTKbwlUwyC6LHKhAzyf4r0T92rNJvbAnU16Sop4M=,iv:u7SJSK140tmttQvM9wDSV8VnAWe8MHbWaS1qLDn9wEU=,tag:aCWh/+ihDVBUbpHewnje/w==,type:str]
    C2XC_EMBEDDING_API_KEY: ENC[AES256_GCM,data:8Al7Jcy2ZlsnjqJOAI2AWFvnuDXLah0DtWMz77Lst2n+2h0=,iv:/3hVVOCM1/fjrWsh1HfDLfLYz8nOdgM2W0Kjr4bwVTQ=,tag:bPkZRjQgO1GH3QbGEuYcNg==,type:str]
sops:
    age:
        - recipient: age1c7psnl4m7ttpwue84y6fsfr5075awz94h8frqm4d6q35xq9xjyjs3dtvn5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYXZuMHFRT0VWT3dIOEJ6
            dGNiT2JQOG8yb0FoT1VPbGc4UEhpdHNiQ21NCkFuZ3pQY29SRll4ZTU1MDRPWlY2
            OWFaN0owZi9DRG1rMlNienptSDNNamcKLS0tIEZwY0d0SUh2b2Zqbzg3QXFmTngw
            MFUvMDYwbDJWQ04zRFB2bmhWL0Q2ZG8KegRDDBgeogaDD3D9CREJoK1EaY8DCMty
            Zv5zLqR8QgbBCkWZWmNqozg+nQNADLJSPxBlvZV7GlZAyfmk2Hv4NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T10:00:13Z"
    mac: ENC[AES256_GCM,data:AFW75l192FPBNsTiS4cVAlnM4cEooudocCSzyrtowUbtRX+038ZvZw53N0GZK5+uFzc4x884pVylPK77S80v1m39elf53qJi7ejdSXjDQvsVgXmDinxqUCATtZdvd3IT3Wpf+N6p1WtH+Uu2QrupNtKyIoMfEBqZdzSofHqX55o=,iv:Q2Fb+H17I7CSeEvrklDAJUNayXQjFLcK/2YxOhCu9i4=,tag:4dZP7gN9gqtvtEXQWP0AHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
